### ISSUE TITLE
does not compile with libpqxx 6.4.4

### ISSUE THREAD

**Issue by jiang-wei** [EOSIO/history-tools#10]
Since [libpqxx 6.4.3 ](https://github.com/jtv/libpqxx/releases/tag/6.4.3)

> The old tablereader and tablewriter headers are no longer included from pqxx/pqxx. They're still there, but you won't automatically include them when you include pqxx/pqxx.

Get compiling error with code on `master`

```
history-tools/src/fill_pg_plugin.cpp:35:11: error: no type named 'tablewriter' in namespace 'pqxx'
    pqxx::tablewriter writer;
    ~~~~~~^
1 error generated.
```
